name: Build APK Otomatis

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Ambil Kode Proyek
      uses: actions/checkout@v4

    - name: Jalankan Buildozer Lewat Server Matang
      uses: ArtemGovorov/buildozer-action@v1
      with:
        workdir: .
        buildozer_version: master
        command: buildozer android debug

    - name: Simpan APK Jadi Ke GitHub
      uses: actions/upload-artifact@v4
      with:
        name: APK-Matang-Anda
        path: bin/*.apk
